name: docker-image

on:
  push:
    branches:
      - main
      - hug
      - huge
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            PORT=7860
            ADMIN=${{ secrets.ADMIN }}
            ADMIN_SECRET=${{ secrets.ADMIN_SECRET }}
            UUID=${{ secrets.UUID }}
            DOMAIN=${{ secrets.DOMAIN }}
            SNI=${{ secrets.SNI }}
            HOST_HEADER=${{ secrets.HOST_HEADER }}
            SUB_PATH=${{ secrets.SUB_PATH }}
            WSPATH=${{ secrets.WSPATH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

